
server:
  port: 7070
 
  servlet:
    context-path: /spring-boot2
 
spring:
  profiles: 
    active: test

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java



a: 
  b: xx








