
server:
  port: 7070
 
  servlet:
    context-path: /
 
spring:
  profiles:
    active:
    - dev

  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java



 # 数据源
datasource: 
  first: 
    jdbc-url: 'jdbc:mysql://127.0.0.1:3306/db_01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai'
    username: root
    password: 'root'
    driver-class-name: com.mysql.jdbc.Driver
    auto-commit: false
    idle-timeout: 180000
    maximum-pool-size: 2000
    minimum-idle: 100
    connection-timeout: 10000
    connection-test-query: SELECT 1
    
  second: 
    jdbc-url: 'jdbc:mysql://127.0.0.1:3306/db_02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai'
    username: root
    password: 'root'
    driver-class-name: com.mysql.jdbc.Driver
    auto-commit: false
    idle-timeout: 180000
    maximum-pool-size: 2000
    minimum-idle: 100
    connection-timeout: 10000
    connection-test-query: SELECT 1





