
server:
  port: 7070
 
  servlet:
    context-path: /
   #context-path: /spring-boot-mvc
  
spring:
  profiles:
    active:
    - dev


  autoconfigure:
    exclude:
    - 


# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: false
      additional-paths:
      - src/main/java

  # 映射资源

  # 静态资源
#  resources:
#    static-locations:
#    - /webjars/**
#    - /static/**

  # favicon.ico 放在 静态资源目录下，或类根路径下都可以
  mvc:
    static-path-pattern: /static/**
    # 
    contentnegotiation:
      favor-parameter: true 
  jackson:
    default-property-inclusion: always
  servlet:
    multipart:
      max-file-size: 10KB
      max-request-size: 20KB
        
      
        




